"""initial schema

Revision ID: 84a40d07b0d9
Revises: 
Create Date: 2026-10-08 06:06:32.822552
"""
from alembic import op
import sqlalchemy as sa


revision = '84a40d07b0d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('est_cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_usage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usage_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usage_provider'), ['provider'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_item_id', sa.String(length=80), nullable=True),
    sa.Column('source_url', sa.String(length=600), nullable=True),
    sa.Column('extraction_method', sa.String(length=80), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('seller', sa.String(length=200), nullable=True),
    sa.Column('domain', sa.String(length=20), nullable=False),
    sa.Column('current_bid', sa.Float(), nullable=True),
    sa.Column('num_bids', sa.Integer(), nullable=True),
    sa.Column('buy_now_price', sa.Float(), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('handling_fee', sa.Float(), nullable=True),
    sa.Column('other_costs', sa.JSON(), nullable=False),
    sa.Column('measurements', sa.JSON(), nullable=False),
    sa.Column('condition_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_item_id', name='uq_listing_source_item')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index('ix_listing_fingerprint', ['fingerprint'], unique=False)

    op.create_table('reference_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('entry_type', sa.String(length=30), nullable=False),
    sa.Column('domain', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('characteristics', sa.Text(), nullable=True),
    sa.Column('identifiers', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('reference_image_urls', sa.JSON(), nullable=False),
    sa.Column('price_evidence', sa.JSON(), nullable=False),
    sa.Column('typical_low', sa.Float(), nullable=True),
    sa.Column('typical_high', sa.Float(), nullable=True),
    sa.Column('demand', sa.String(length=10), nullable=False),
    sa.Column('liquidity', sa.String(length=10), nullable=False),
    sa.Column('id_confidence_notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reference_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reference_entries_name'), ['name'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('est_cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_runs_input_hash'), ['input_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_listing_id'), ['listing_id'], unique=False)

    op.create_table('comparables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('marketplace', sa.String(length=60), nullable=False),
    sa.Column('url', sa.String(length=800), nullable=True),
    sa.Column('sold_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('shipping_included', sa.Boolean(), nullable=True),
    sa.Column('shipping_amount', sa.Float(), nullable=True),
    sa.Column('is_sold', sa.Boolean(), nullable=False),
    sa.Column('accepted_offer', sa.Boolean(), nullable=False),
    sa.Column('comp_type', sa.String(length=20), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('evidence_quality', sa.String(length=10), nullable=False),
    sa.Column('condition', sa.String(length=200), nullable=True),
    sa.Column('differences', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_id'], ['reference_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comparables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comparables_listing_id'), ['listing_id'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_listing_id'), ['listing_id'], unique=False)

    op.create_table('listing_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('remote_url', sa.String(length=800), nullable=True),
    sa.Column('local_path', sa.String(length=600), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fetch_error', sa.String(length=300), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_images_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_images_sha256'), ['sha256'], unique=False)

    op.create_table('listing_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('current_bid', sa.Float(), nullable=True),
    sa.Column('num_bids', sa.Integer(), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_snapshots_listing_id'), ['listing_id'], unique=False)

    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=30), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('finance', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id')
    )
    op.create_table('outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('purchased', sa.Boolean(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('acquisition_expenses', sa.Float(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold', sa.Boolean(), nullable=False),
    sa.Column('resale_price', sa.Float(), nullable=True),
    sa.Column('selling_fees', sa.Float(), nullable=True),
    sa.Column('resale_platform', sa.String(length=40), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('days_to_sale', sa.Integer(), nullable=True),
    sa.Column('realized_profit', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id')
    )
    op.create_table('research_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_notes_listing_id'), ['listing_id'], unique=False)

    op.create_table('valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('conservative', sa.Float(), nullable=True),
    sa.Column('expected', sa.Float(), nullable=True),
    sa.Column('optimistic', sa.Float(), nullable=True),
    sa.Column('is_speculative', sa.Boolean(), nullable=False),
    sa.Column('evidence_quality', sa.String(length=10), nullable=False),
    sa.Column('n_sold_comps', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('valuations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valuations_listing_id'), ['listing_id'], unique=False)

    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('user_max_bid', sa.Float(), nullable=True),
    sa.Column('remind_minutes_before_end', sa.Integer(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id')
    )
    op.create_table('identifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('domain', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('discrepancy', sa.JSON(), nullable=False),
    sa.Column('warrants_research', sa.Boolean(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identifications_listing_id'), ['listing_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identifications_listing_id'))

    op.drop_table('identifications')
    op.drop_table('watchlist')
    with op.batch_alter_table('valuations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valuations_listing_id'))

    op.drop_table('valuations')
    with op.batch_alter_table('research_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_notes_listing_id'))

    op.drop_table('research_notes')
    op.drop_table('outcomes')
    op.drop_table('opportunities')
    with op.batch_alter_table('listing_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_snapshots_listing_id'))

    op.drop_table('listing_snapshots')
    with op.batch_alter_table('listing_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_images_sha256'))
        batch_op.drop_index(batch_op.f('ix_listing_images_listing_id'))

    op.drop_table('listing_images')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_listing_id'))

    op.drop_table('feedback')
    with op.batch_alter_table('comparables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comparables_listing_id'))

    op.drop_table('comparables')
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_runs_listing_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_input_hash'))

    op.drop_table('analysis_runs')
    op.drop_table('settings')
    with op.batch_alter_table('reference_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reference_entries_name'))

    op.drop_table('reference_entries')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index('ix_listing_fingerprint')

    op.drop_table('listings')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_listing_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_job_type'))

    op.drop_table('jobs')
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_usage_provider'))
        batch_op.drop_index(batch_op.f('ix_api_usage_listing_id'))
        batch_op.drop_index(batch_op.f('ix_api_usage_created_at'))

    op.drop_table('api_usage')
    # ### end Alembic commands ###
